#!/usr/bin/env python3
"""Generate optional grouped Python wrappers from the shared C ABI model."""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path

from steamworks_model import python_snake_name, split_words

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MODEL = ROOT / "generated" / "steamworks_c_api_model.json"
DEFAULT_OUTPUT = ROOT / "python" / "steamworks" / "grouped.py"


def class_name(interface: str) -> str:
    return "_" + "".join(word[:1].upper() + word[1:] for word in split_words(interface)) + "API"


def instance_name(interface: str) -> str:
    if interface == "Global/static":
        return ""
    return python_snake_name(interface)


def param_name(value: str) -> str:
    result = python_snake_name(value)
    if not result:
        result = "arg"
    return result


def helper_method_name(interface: str, cpp_name: str, c_name: str, *, drop_get: bool = True) -> str:
    name = cpp_name or c_name.removeprefix("SWS_")
    if name.startswith("Steam_"):
        name = name[len("Steam_"):]
    if interface and interface != "Global/static":
        prefix = interface + "_"
        if name.startswith(prefix):
            name = name[len(prefix):]
    return python_snake_name(name, drop_get=drop_get)


def method_candidates(model: dict) -> list[tuple[str, str, str, dict]]:
    candidates = []
    for method in model.get("methods", []):
        interface = method.get("interface")
        c_name = method.get("c_name")
        cpp_name = method.get("cpp_name")
        if not interface or not c_name:
            continue
        if method.get("source") == "sdk":
            method_name = method.get("friendly_name") or method.get("methodname")
            if not method_name:
                continue
            grouped_name = python_snake_name(method_name)
        else:
            grouped_name = helper_method_name(interface, cpp_name or "", c_name)
        candidates.append((interface, grouped_name, c_name, method))
    return candidates


def generate(model: dict) -> str:
    candidates = method_candidates(model)
    counts = Counter((interface, name) for interface, name, _, _ in candidates)
    interfaces: dict[str, list[dict]] = {}
    module_functions: list[dict] = []

    for interface, grouped_name, c_name, method in candidates:
        if counts[(interface, grouped_name)] > 1:
            if method.get("source") == "sdk":
                flat_name = method.get("flat_name") or c_name
                prefix = f"SteamAPI_ISteam{interface}_"
                grouped_name = python_snake_name(flat_name.removeprefix(prefix), drop_get=False)
            else:
                grouped_name = helper_method_name(interface, method.get("cpp_name") or "", c_name, drop_get=False)

        params = []
        arg_names = []
        seen_params: Counter[str] = Counter()
        for param in method.get("params", []):
            name = param_name(param.get("name", "arg"))
            seen_params[name] += 1
            if seen_params[name] > 1:
                name = f"{name}_{seen_params[name]}"
            params.append(name)
            arg_names.append(name)

        interfaces.setdefault(interface, []).append(
            {
                "name": grouped_name,
                "c_name": c_name,
                "params": params,
                "arg_names": arg_names,
            }
        )

    lines = [
        '"""Grouped Python wrappers for the generated Steamworks module."""',
        "",
        "# Code generated by tools/generate_python.py; DO NOT EDIT.",
        "",
        "from . import steamworks as _raw",
        "",
    ]

    exported = []
    for interface in sorted(interfaces):
        if interface == "Global/static":
            module_functions.extend(interfaces[interface])
            continue
        cls = class_name(interface)
        instance = instance_name(interface)
        exported.append(instance)
        lines.extend([f"class {cls}:", ""])
        for item in sorted(interfaces[interface], key=lambda value: value["name"]):
            params = ", ".join(["self"] + item["params"])
            args = ", ".join(item["arg_names"])
            call = f'_raw.{item["c_name"]}({args})' if args else f'_raw.{item["c_name"]}()'
            lines.append(f"    def {item['name']}({params}):")
            lines.append(f"        return {call}")
            lines.append("")
        lines.extend([f"{instance} = {cls}()", ""])

    for item in sorted(module_functions, key=lambda value: value["name"]):
        exported.append(item["name"])
        params = ", ".join(item["params"])
        args = ", ".join(item["arg_names"])
        call = f'_raw.{item["c_name"]}({args})' if args else f'_raw.{item["c_name"]}()'
        lines.append(f"def {item['name']}({params}):")
        lines.append(f"    return {call}")
        lines.append("")

    lines.append(f"__all__ = {exported!r}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", default=str(DEFAULT_MODEL), help="Path to steamworks_c_api_model.json")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="Python output path")
    args = parser.parse_args()

    model_path = Path(args.model)
    output_path = Path(args.output)
    model = json.loads(model_path.read_text(encoding="utf-8"))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(generate(model), encoding="utf-8")
    print(f"Wrote {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
