"""Curated C ABI helper function metadata."""

from __future__ import annotations

C_MANUAL_FUNCTIONS = [
    ("bool", "Steam_Init", []),
    ("int", "Steam_InitEx", []),
    ("int", "Steam_InitFlat", []),
    ("void", "Steam_Shutdown", []),
    ("void", "Steam_ClearHelperState", []),
    ("void", "Steam_RunCallbacks", []),
    ("int", "Steam_GetCallbackDispatchMode", []),
    ("int", "Steam_CallbackDispatchModeUninitialized", []),
    ("int", "Steam_CallbackDispatchModeAutomatic", []),
    ("int", "Steam_CallbackDispatchModeManual", []),
    ("bool", "Steam_IsSteamRunning", []),
    ("bool", "Steam_RestartAppIfNecessary", [("AppId_t", "appID")]),
    ("void", "Steam_ReleaseCurrentThreadMemory", []),
    ("const char *", "Steam_GetSteamInstallPath", []),
    ("void", "Steam_SetTryCatchCallbacks", [("bool", "enabled")]),
    ("void", "Steam_SetMiniDumpComment", [("const char *", "message")]),
    ("HSteamPipe", "Steam_GetHSteamPipe", []),
    ("HSteamUser", "Steam_GetHSteamUser", []),
    ("int", "Steam_GetLastInitResult", []),
    ("const char *", "Steam_GetLastInitError", []),
    (
        "bool",
        "Steam_GameServer_Init",
        [
            ("uint32", "ip"),
            ("uint16", "gamePort"),
            ("uint16", "queryPort"),
            ("int", "serverMode"),
            ("const char *", "versionString"),
        ],
    ),
    (
        "int",
        "Steam_GameServer_InitEx",
        [
            ("uint32", "ip"),
            ("uint16", "gamePort"),
            ("uint16", "queryPort"),
            ("int", "serverMode"),
            ("const char *", "versionString"),
        ],
    ),
    ("void", "Steam_GameServer_Shutdown", []),
    ("void", "Steam_GameServer_RunCallbacks", []),
    ("void", "Steam_GameServer_ReleaseCurrentThreadMemory", []),
    ("bool", "Steam_GameServer_GlobalBSecure", []),
    ("uint64", "Steam_GameServer_GlobalGetSteamID", []),
    ("HSteamPipe", "Steam_GameServer_GetHSteamPipe", []),
    ("HSteamUser", "Steam_GameServer_GetHSteamUser", []),
    ("int", "Steam_GameServer_GetLastInitResult", []),
    ("const char *", "Steam_GameServer_GetLastInitError", []),
    ("int", "Steam_ServerModeInvalid", []),
    ("int", "Steam_ServerModeNoAuthentication", []),
    ("int", "Steam_ServerModeAuthentication", []),
    ("int", "Steam_ServerModeAuthenticationAndSecure", []),
    ("uint16", "Steam_GameServer_QueryPortShared", []),
    ("SteamAPICall_t", "Steam_Lobby_RequestList", []),
    ("bool", "Steam_Lobby_IsListPending", []),
    ("bool", "Steam_Lobby_IsListComplete", []),
    ("bool", "Steam_Lobby_ListHadIOFailure", []),
    ("uint32", "Steam_Lobby_GetListResultCount", []),
    ("uint64_steamid", "Steam_Lobby_GetListLobbyByIndex", [("int", "index")]),
    ("std::string", "Steam_Lobby_GetListLobbyNameByIndex", [("int", "index")]),
    ("void", "Steam_Lobby_ClearAsyncState", []),
]

C_HELPER_FUNCTIONS = [
    ("SteamworksBytes", "Steam_User_GetLastAuthSessionTicketBytes", []),
    ("HAuthTicket", "Steam_User_GetAuthSessionTicketBytes", [("int", "maxTicketSize")]),
    ("int", "Steam_User_BeginAuthSessionBytes", [("const char *", "data"), ("size_t", "dataSize"), ("uint64_steamid", "steamID")]),
    ("SteamAPICall_t", "Steam_User_RequestEncryptedAppTicketBytes", [("const char *", "data"), ("size_t", "dataSize")]),
    ("SteamworksBytes", "Steam_User_GetEncryptedAppTicketBytes", [("int", "maxTicketSize")]),
    ("std::string", "Steam_Apps_GetDLCDataByIndexString", [("int", "dlcIndex")]),
    ("std::string", "Steam_Apps_GetTimedTrialString", []),
    ("std::string", "Steam_Apps_GetAppInstallDirString", [("AppId_t", "appID")]),
    ("std::string", "Steam_Apps_GetBetaInfoString", [("int", "betaIndex")]),
    ("std::string", "Steam_Apps_GetCurrentBetaNameString", []),
    ("std::string", "Steam_Apps_GetDlcDownloadProgressString", [("AppId_t", "appID")]),
    ("std::vector<std::string>", "Steam_Apps_GetInstalledDepotsList", [("AppId_t", "appID")]),
    ("std::string", "Steam_Apps_GetLaunchCommandLineString", []),
    ("std::string", "Steam_Apps_GetNumBetasString", []),
    ("std::vector<std::string>", "Steam_Inventory_GetItemDefinitionIDsList", []),
    ("std::string", "Steam_Inventory_GetItemDefinitionPropertyString", [("SteamItemDef_t", "definition"), ("const char *", "propertyName")]),
    ("std::string", "Steam_Inventory_GetItemPriceString", [("SteamItemDef_t", "definition")]),
    ("std::vector<std::string>", "Steam_Inventory_GetItemsWithPricesList", []),
    ("std::string", "Steam_Inventory_GetResultItemPropertyString", [("SteamInventoryResult_t", "resultHandle"), ("uint32", "itemIndex"), ("const char *", "propertyName")]),
    ("std::string", "Steam_UGC_GetItemDownloadInfoString", [("PublishedFileId_t", "publishedFileID")]),
    ("std::string", "Steam_UGC_GetItemInstallInfoString", [("PublishedFileId_t", "publishedFileID")]),
    ("std::string", "Steam_UGC_GetItemUpdateProgressString", [("UGCUpdateHandle_t", "updateHandle")]),
    ("std::string", "Steam_UGC_GetQueryUGCAdditionalPreviewString", [("UGCQueryHandle_t", "queryHandle"), ("uint32", "index"), ("uint32", "previewIndex")]),
    ("std::string", "Steam_UGC_GetQueryUGCKeyValueTagByIndexString", [("UGCQueryHandle_t", "queryHandle"), ("uint32", "index"), ("uint32", "tagIndex")]),
    ("std::string", "Steam_UGC_GetQueryUGCKeyValueTagValueString", [("UGCQueryHandle_t", "queryHandle"), ("uint32", "index"), ("const char *", "key")]),
    ("std::string", "Steam_UGC_GetQueryUGCMetadataString", [("UGCQueryHandle_t", "queryHandle"), ("uint32", "index")]),
    ("std::string", "Steam_UGC_GetQueryUGCPreviewURLString", [("UGCQueryHandle_t", "queryHandle"), ("uint32", "index")]),
    ("std::string", "Steam_UGC_GetQueryUGCTagDisplayNameString", [("UGCQueryHandle_t", "queryHandle"), ("uint32", "index"), ("uint32", "tagIndex")]),
    ("std::string", "Steam_UGC_GetQueryUGCTagString", [("UGCQueryHandle_t", "queryHandle"), ("uint32", "index"), ("uint32", "tagIndex")]),
    ("std::string", "Steam_UGC_GetSupportedGameVersionDataString", [("UGCQueryHandle_t", "queryHandle"), ("uint32", "index"), ("uint32", "versionIndex")]),
    ("std::string", "Steam_User_GetAvailableVoiceString", [("uint32", "sampleRate")]),
    ("std::string", "Steam_User_GetUserDataFolderString", []),
    ("std::string", "Steam_Utils_FilterTextString", [("int", "context"), ("uint64_steamid", "sourceSteamID"), ("const char *", "inputMessage")]),
    ("std::string", "Steam_Utils_GetEnteredGamepadTextInputString", []),
    ("std::string", "Steam_Utils_GetImageSizeString", [("int", "image")]),
    ("std::string", "Steam_Video_IsBroadcastingString", []),
    ("SteamworksBytes", "Steam_GameServer_GetLastAuthSessionTicketBytes", []),
    ("HAuthTicket", "Steam_GameServer_GetAuthSessionTicketBytes", [("int", "maxTicketSize")]),
    ("int", "Steam_GameServer_BeginAuthSessionBytes", [("const char *", "data"), ("size_t", "dataSize"), ("uint64_steamid", "steamID")]),
    ("HSteamListenSocket", "Steam_NetworkingSockets_CreateListenSocketIPStringNoOptions", [("const char *", "address")]),
    ("HSteamNetConnection", "Steam_NetworkingSockets_ConnectByIPAddressStringNoOptions", [("const char *", "address")]),
    ("HSteamListenSocket", "Steam_NetworkingSockets_CreateListenSocketP2PNoOptions", [("int", "localVirtualPort")]),
    ("HSteamNetConnection", "Steam_NetworkingSockets_ConnectP2PSteamIDNoOptions", [("uint64_steamid", "steamID"), ("int", "remoteVirtualPort")]),
    ("void", "Steam_NetworkingSockets_EnableConnectionStatusCallbacks", []),
    ("void", "Steam_NetworkingSockets_ClearConnectionStatusChangedEvents", []),
    ("std::vector<std::string>", "Steam_NetworkingSockets_PollConnectionStatusChangedStrings", [("int", "maxEvents")]),
    ("int", "Steam_NetworkingSockets_SendMessageToConnectionString", [("HSteamNetConnection", "connection"), ("const char *", "data"), ("int", "sendFlags")]),
    ("int", "Steam_NetworkingSockets_SendMessageToConnectionBytes", [("HSteamNetConnection", "connection"), ("const char *", "data"), ("size_t", "dataSize"), ("int", "sendFlags")]),
    ("std::vector<std::string>", "Steam_NetworkingSockets_ReceiveMessagesOnConnectionStrings", [("HSteamNetConnection", "connection"), ("int", "maxMessages")]),
    ("SteamworksBytesVector", "Steam_NetworkingSockets_ReceiveMessagesOnConnectionBytes", [("HSteamNetConnection", "connection"), ("int", "maxMessages")]),
    ("std::vector<std::string>", "Steam_NetworkingSockets_ReceiveMessagesOnPollGroupStrings", [("HSteamNetPollGroup", "pollGroup"), ("int", "maxMessages")]),
    ("SteamworksBytesVector", "Steam_NetworkingSockets_ReceiveMessagesOnPollGroupBytes", [("HSteamNetPollGroup", "pollGroup"), ("int", "maxMessages")]),
    ("std::string", "Steam_NetworkingSockets_GetConnectionNameString", [("HSteamNetConnection", "connection")]),
    ("std::string", "Steam_NetworkingSockets_GetConnectionInfoString", [("HSteamNetConnection", "connection")]),
    ("std::string", "Steam_NetworkingSockets_GetConnectionRealTimeStatusString", [("HSteamNetConnection", "connection")]),
    ("std::string", "Steam_NetworkingSockets_GetDetailedConnectionStatusString", [("HSteamNetConnection", "connection")]),
    ("std::string", "Steam_NetworkingSockets_GetListenSocketAddressString", [("HSteamListenSocket", "listenSocket")]),
    ("std::string", "Steam_NetworkingSockets_GetIdentityString", []),
    ("std::string", "Steam_NetworkingSockets_GetAuthenticationStatusString", []),
    ("std::string", "Steam_NetworkingSockets_GetFakeIPString", [("int", "firstPortIndex")]),
    ("HSteamListenSocket", "Steam_NetworkingSockets_CreateListenSocketP2PFakeIPNoOptions", [("int", "fakePortIndex")]),
    ("std::string", "Steam_NetworkingSockets_GetRemoteFakeIPForConnectionString", [("HSteamNetConnection", "connection")]),
    ("HSteamListenSocket", "Steam_GameServerNetworkingSockets_CreateListenSocketP2PNoOptions", [("int", "localVirtualPort")]),
    ("HSteamNetPollGroup", "Steam_GameServerNetworkingSockets_CreatePollGroup", []),
    ("bool", "Steam_GameServerNetworkingSockets_DestroyPollGroup", [("HSteamNetPollGroup", "pollGroup")]),
    ("int", "Steam_GameServerNetworkingSockets_AcceptConnection", [("HSteamNetConnection", "connection")]),
    ("bool", "Steam_GameServerNetworkingSockets_CloseConnection", [("HSteamNetConnection", "connection"), ("int", "reason"), ("const char *", "debugMessage"), ("bool", "enableLinger")]),
    ("bool", "Steam_GameServerNetworkingSockets_CloseListenSocket", [("HSteamListenSocket", "listenSocket")]),
    ("bool", "Steam_GameServerNetworkingSockets_SetConnectionPollGroup", [("HSteamNetConnection", "connection"), ("HSteamNetPollGroup", "pollGroup")]),
    ("int", "Steam_GameServerNetworkingSockets_SendMessageToConnectionString", [("HSteamNetConnection", "connection"), ("const char *", "data"), ("int", "sendFlags")]),
    ("int", "Steam_GameServerNetworkingSockets_SendMessageToConnectionBytes", [("HSteamNetConnection", "connection"), ("const char *", "data"), ("size_t", "dataSize"), ("int", "sendFlags")]),
    ("std::vector<std::string>", "Steam_GameServerNetworkingSockets_ReceiveMessagesOnConnectionStrings", [("HSteamNetConnection", "connection"), ("int", "maxMessages")]),
    ("SteamworksBytesVector", "Steam_GameServerNetworkingSockets_ReceiveMessagesOnConnectionBytes", [("HSteamNetConnection", "connection"), ("int", "maxMessages")]),
    ("std::vector<std::string>", "Steam_GameServerNetworkingSockets_ReceiveMessagesOnPollGroupStrings", [("HSteamNetPollGroup", "pollGroup"), ("int", "maxMessages")]),
    ("SteamworksBytesVector", "Steam_GameServerNetworkingSockets_ReceiveMessagesOnPollGroupBytes", [("HSteamNetPollGroup", "pollGroup"), ("int", "maxMessages")]),
    ("int", "Steam_NetworkingMessages_SendMessageToSteamIDBytes", [("uint64_steamid", "steamID"), ("const char *", "data"), ("size_t", "dataSize"), ("int", "sendFlags"), ("int", "remoteChannel")]),
    ("SteamworksBytesVector", "Steam_NetworkingMessages_ReceiveMessagesOnChannelBytes", [("int", "localChannel"), ("int", "maxMessages")]),
    ("bool", "Steam_NetworkingMessages_AcceptSessionWithSteamID", [("uint64_steamid", "steamID")]),
    ("bool", "Steam_NetworkingMessages_CloseSessionWithSteamID", [("uint64_steamid", "steamID")]),
    ("bool", "Steam_NetworkingMessages_CloseChannelWithSteamID", [("uint64_steamid", "steamID"), ("int", "localChannel")]),
    ("int", "Steam_GameServerNetworkingMessages_SendMessageToSteamIDBytes", [("uint64_steamid", "steamID"), ("const char *", "data"), ("size_t", "dataSize"), ("int", "sendFlags"), ("int", "remoteChannel")]),
    ("SteamworksBytesVector", "Steam_GameServerNetworkingMessages_ReceiveMessagesOnChannelBytes", [("int", "localChannel"), ("int", "maxMessages")]),
    ("bool", "Steam_GameServerNetworkingMessages_AcceptSessionWithSteamID", [("uint64_steamid", "steamID")]),
    ("bool", "Steam_GameServerNetworkingMessages_CloseSessionWithSteamID", [("uint64_steamid", "steamID")]),
    ("bool", "Steam_GameServerNetworkingMessages_CloseChannelWithSteamID", [("uint64_steamid", "steamID"), ("int", "localChannel")]),
    ("bool", "Steam_RemoteStorage_FileWriteBytes", [("const char *", "filename"), ("const char *", "data"), ("size_t", "dataSize")]),
    ("SteamworksBytes", "Steam_RemoteStorage_FileReadBytes", [("const char *", "filename"), ("int32", "dataSize")]),
    ("SteamAPICall_t", "Steam_RemoteStorage_FileWriteAsyncBytes", [("const char *", "filename"), ("const char *", "data"), ("size_t", "dataSize")]),
    ("SteamworksBytes", "Steam_RemoteStorage_FileReadAsyncCompleteBytes", [("SteamAPICall_t", "readCall"), ("uint32", "dataSize")]),
    ("bool", "Steam_RemoteStorage_FileWriteStreamWriteChunkBytes", [("UGCFileWriteStreamHandle_t", "writeHandle"), ("const char *", "data"), ("size_t", "dataSize")]),
    ("bool", "Steam_HTTP_SetHTTPRequestRawPostBodyBytes", [("HTTPRequestHandle", "request"), ("const char *", "contentType"), ("const char *", "data"), ("size_t", "dataSize")]),
    ("SteamworksBytes", "Steam_HTTP_GetHTTPResponseBodyDataBytes", [("HTTPRequestHandle", "request"), ("uint32", "dataSize")]),
    ("SteamworksBytes", "Steam_HTTP_GetHTTPStreamingResponseBodyDataBytes", [("HTTPRequestHandle", "request"), ("uint32", "offset"), ("uint32", "dataSize")]),
    ("bool", "Steam_GameServerHTTP_SetHTTPRequestRawPostBodyBytes", [("HTTPRequestHandle", "request"), ("const char *", "contentType"), ("const char *", "data"), ("size_t", "dataSize")]),
    ("SteamworksBytes", "Steam_GameServerHTTP_GetHTTPResponseBodyDataBytes", [("HTTPRequestHandle", "request"), ("uint32", "dataSize")]),
    ("SteamworksBytes", "Steam_GameServerHTTP_GetHTTPStreamingResponseBodyDataBytes", [("HTTPRequestHandle", "request"), ("uint32", "offset"), ("uint32", "dataSize")]),
    ("int", "Steam_NetworkingSend_Unreliable", []),
    ("int", "Steam_NetworkingSend_UnreliableNoDelay", []),
    ("int", "Steam_NetworkingSend_Reliable", []),
    ("int", "Steam_NetworkingSend_ReliableNoNagle", []),
    ("int", "Steam_NetworkingConnectionState_None", []),
    ("int", "Steam_NetworkingConnectionState_Connecting", []),
    ("int", "Steam_NetworkingConnectionState_FindingRoute", []),
    ("int", "Steam_NetworkingConnectionState_Connected", []),
    ("int", "Steam_NetworkingConnectionState_ClosedByPeer", []),
    ("int", "Steam_NetworkingConnectionState_ProblemDetectedLocally", []),
    ("int", "Steam_NetConnectionEnd_AppGeneric", []),
    ("int", "Steam_NetConnectionEnd_AppExceptionGeneric", []),
    ("std::vector<std::string>", "Steam_Lobby_GetDataEntries", [("uint64_steamid", "lobbyID")]),
    ("SteamAPICall_t", "Steam_Lobby_Create", [("int", "lobbyType"), ("int", "maxMembers")]),
    ("bool", "Steam_Lobby_IsCreatePending", []),
    ("bool", "Steam_Lobby_IsCreateComplete", []),
    ("bool", "Steam_Lobby_CreateHadIOFailure", []),
    ("uint64_steamid", "Steam_Lobby_GetCreatedLobbyID", []),
    ("int", "Steam_Lobby_GetCreateResult", []),
    ("bool", "Steam_Lobby_CreateSucceeded", []),
    ("SteamAPICall_t", "Steam_Lobby_Join", [("uint64_steamid", "lobbyID")]),
    ("bool", "Steam_Lobby_IsJoinPending", []),
    ("bool", "Steam_Lobby_IsJoinComplete", []),
    ("bool", "Steam_Lobby_JoinHadIOFailure", []),
    ("uint64_steamid", "Steam_Lobby_GetJoinedLobbyID", []),
    ("uint32", "Steam_Lobby_GetJoinResponse", []),
    ("bool", "Steam_Lobby_JoinSucceeded", []),
    ("int", "Steam_Lobby_ChatRoomEnterResponseSuccess", []),
    ("void", "Steam_Lobby_EnableChatCallbacks", []),
    ("void", "Steam_Lobby_ClearChatMessages", []),
    ("bool", "Steam_Lobby_SendChatMessage", [("uint64_steamid", "lobbyID"), ("const char *", "message")]),
    ("std::vector<std::string>", "Steam_Lobby_PollChatMessages", [("int", "maxMessages")]),
    ("HServerQuery", "Steam_MatchmakingServers_PingServer", [("uint32", "ip"), ("uint16", "port")]),
    ("bool", "Steam_MatchmakingServers_IsPingPending", []),
    ("bool", "Steam_MatchmakingServers_IsPingComplete", []),
    ("bool", "Steam_MatchmakingServers_PingFailed", []),
    ("bool", "Steam_MatchmakingServers_PingSucceeded", []),
    ("std::string", "Steam_MatchmakingServers_GetPingServer", []),
    ("void", "Steam_MatchmakingServers_ClearPingResult", []),
    ("HServerQuery", "Steam_MatchmakingServers_ServerFriends", [("uint32", "ip"), ("uint16", "port")]),
    ("bool", "Steam_MatchmakingServers_IsServerFriendsPending", []),
    ("bool", "Steam_MatchmakingServers_IsServerFriendsComplete", []),
    ("bool", "Steam_MatchmakingServers_ServerFriendsFailed", []),
    ("bool", "Steam_MatchmakingServers_ServerFriendsSucceeded", []),
    ("std::vector<std::string>", "Steam_MatchmakingServers_GetServerFriends", []),
    ("void", "Steam_MatchmakingServers_ClearServerFriendsResult", []),
    ("int", "Steam_FriendFlagImmediate", []),
    ("int", "Steam_FriendFlagOnGameServer", []),
    ("int", "Steam_FriendFlagAll", []),
    ("int", "Steam_LobbyTypePrivate", []),
    ("int", "Steam_LobbyTypeFriendsOnly", []),
    ("int", "Steam_LobbyTypePublic", []),
    ("int", "Steam_LobbyTypeInvisible", []),
    ("int", "Steam_LobbyTypePrivateUnique", []),
    ("int", "Steam_LobbyComparisonEqual", []),
    ("int", "Steam_PersonaStateOffline", []),
    ("int", "Steam_PersonaStateOnline", []),
    ("int", "Steam_PersonaStateBusy", []),
    ("int", "Steam_PersonaStateAway", []),
    ("int", "Steam_PersonaStateSnooze", []),
    ("int", "Steam_PersonaStateLookingToTrade", []),
    ("int", "Steam_PersonaStateLookingToPlay", []),
    ("int", "Steam_PersonaStateInvisible", []),
    ("int", "Steam_Friends_GetFriendCountImmediate", []),
    ("uint64_steamid", "Steam_Friends_GetFriendByIndexImmediate", [("int", "index")]),
    ("bool", "Steam_Friends_GetFriendGamePlayedInfo", [("uint64_steamid", "friendID")]),
    ("uint64_gameid", "Steam_Friends_GetFriendGameID", [("uint64_steamid", "friendID")]),
    ("AppId_t", "Steam_Friends_GetFriendGameAppID", [("uint64_steamid", "friendID")]),
    ("uint32", "Steam_Friends_GetFriendGameIP", [("uint64_steamid", "friendID")]),
    ("uint16", "Steam_Friends_GetFriendGamePort", [("uint64_steamid", "friendID")]),
    ("uint16", "Steam_Friends_GetFriendGameQueryPort", [("uint64_steamid", "friendID")]),
    ("uint64_steamid", "Steam_Friends_GetFriendGameLobbyID", [("uint64_steamid", "friendID")]),
    ("bool", "Steam_Friends_IsFriendInCurrentGame", [("uint64_steamid", "friendID")]),
]

MANUAL_DISPATCH_FUNCTIONS = [
    ("void", "Steam_ManualDispatch_Init", []),
    ("void", "Steam_ManualDispatch_RunFrame", [("HSteamPipe", "pipe")]),
    ("bool", "Steam_ManualDispatch_GetNextCallback", [("HSteamPipe", "pipe")]),
    ("HSteamUser", "Steam_ManualDispatch_GetCallbackSteamUser", []),
    ("int", "Steam_ManualDispatch_GetCallbackID", []),
    ("std::string", "Steam_ManualDispatch_GetCallbackData", []),
    ("int", "Steam_ManualDispatch_GetCallbackSize", []),
    ("bool", "Steam_ManualDispatch_CallbackIsAPICallCompleted", []),
    ("SteamAPICall_t", "Steam_ManualDispatch_GetCompletedAPICall", []),
    ("int", "Steam_ManualDispatch_GetCompletedCallbackID", []),
    ("uint32", "Steam_ManualDispatch_GetCompletedCallbackSize", []),
    (
        "bool",
        "Steam_ManualDispatch_GetAPICallResult",
        [
            ("HSteamPipe", "pipe"),
            ("SteamAPICall_t", "apiCall"),
            ("int", "callbackSize"),
            ("int", "callbackID"),
        ],
    ),
    ("std::string", "Steam_ManualDispatch_GetAPICallResultData", []),
    ("bool", "Steam_ManualDispatch_GetAPICallResultFailed", []),
    ("int", "Steam_ManualDispatch_CallbackIDSteamAPICallCompleted", []),
    ("void", "Steam_ManualDispatch_FreeLastCallback", [("HSteamPipe", "pipe")]),
]
